config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'welcome', to: 'pages#welcome', as: :welcome

  get 'parse', to: 'pages#email_parse', as: :email_parse
  post 'parse', to: 'pages#email_parse'
  post 'email_processor', to: 'griddler/emails#create'

  resources :organizations do
    resources :teams, only: [:show, :new, :edit, :create, :update] do
      resources :participations, only:[:new, :create, :destroy]
      resources :meetings, only:[:index,:show, :new, :edit, :create, :update] do
        resources :invitations, only:[:new, :create, :edit] do
          collection do
            get :invite_someone
            post :send_invites

          end
        end
      end
    end
  end
  resources :teams, only: [:destroy]
  resources :meetings, only: [:destroy]
  resources :invitations, only:[:destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  belongs_to :team, optional: true
  belongs_to :organization
  has_many :invitations, dependent: :destroy
  has_many :users, through: :invitations
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :find_organization
  skip_before_action :find_organization, only:[:destroy]
  def index
    @meetings = Meeting.all
  end

  def show
    @meeting = Meeting.find(params[:id])
    authorize @meeting
    @user = current_user
    @team = find_team
  end

  def new
    @meeting = Meeting.new
    @meeting.organization = find_organization
    @meeting.team = find_team
    authorize @meeting
  end

  def create
    @meeting  = Meeting.new(meeting_params)
    @meeting.organization = find_organization
    @meeting.team = find_team
    @meeting.user = current_user
    authorize @meeting
    if @meeting.save
      redirect_to new_organization_team_meeting_invitation_path(@organization, @team, @meeting), notice: 'La reunión fue creada'
    else
      render :new
    end
  end

  def edit
    @meeting = Meeting.find(params[:id])
    authorize @meeting
  end
  def update
    @meeting = Meeting.find(params[:id])
    @meeting.name = meeting_params[:name]
    authorize @meeting
    if @meeting.save
      redirect_to organization_team_meeting_path(@organization, @team, @meeting), notice: 'La reunión fue creada'
    else
      render :new
    end
  end
  def destroy

    @meeting = Meeting.find(params[:id])
    authorize @meeting
    @meeting.destroy!
    redirect_to organization_team_path(@meeting.organization, @meeting.team), notice: 'La reunión fue eliminada'

  end


  private
  def meeting_params
    params.require(:meeting).permit(:name)
  end

  def find_team
    @team = Team.find(params[:team_id])
  end

  def find_organization
    @organization = Organization.find(params[:organization_id])
  end
end

app/views/meetings/_form.html.erb
<%= simple_form_for [@organization, @team, @meeting] do |f| %>
<%= f.input :name, label: 'Nombre de la Reunión' %>
<%= f.submit %>
<% end %>

app/views/meetings/new.html.erb
<%= render 'form' %>

app/views/meetings/show.html.erb
<h1><%= @meeting.name %></h1>
<p>Creada por <%=@meeting.user.name%> <%= @user.last_name%> fecha de creación: <%= @meeting.created_at%></p>
<% if policy(@meeting).destroy? %>
<p><%= link_to "Eliminar esta reunión", meeting_path, method: :delete, data: { confirm: "Confirme esta acción por favor" } %></p>
<% end %>
<strong>Organizacón</strong>
<p>
<%= link_to @organization.name, organization_path(@organization)%>
</p>
<strong>Equipo</strong>
<p>
<%= link_to @team.name, organization_team_path(@team)%>
</p>
<strong>Invitados</strong>
<%= link_to "Editar invitados",edit_organization_team_meeting_invitation_path(@organization, @team, @meeting) %>
<ol>
  <% @meeting.invitations.each do |invitation|%>
  <li><%= invitation.user.name %></li>
  <% end %>
</ol>