config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'welcome', to: 'pages#welcome', as: :welcome

  get 'parse', to: 'pages#email_parse', as: :email_parse
  post 'parse', to: 'pages#email_parse'
  post 'email_processor', to: 'griddler/emails#create'

  resources :organizations do
    resources :teams, only: [:show, :new, :edit, :create, :update] do
      resources :participations, only:[:new, :create, :destroy]
      resources :meetings, only:[:index,:show, :new, :edit, :create, :update] do
        resources :invitations, only:[:new, :create, :edit] do
          collection do
            get :invite_someone
            post :send_invites

          end
        end
      end
    end
  end
  resources :teams, only: [:destroy]
  resources :meetings, only: [:destroy]
  resources :invitations, only:[:destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
  belongs_to :meeting
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :find_organization
  before_action :find_team
  before_action :find_meeting
  skip_before_action :find_organization, only:[:destroy]
  skip_before_action :find_team, only:[:destroy]
  skip_before_action :find_meeting, only:[:destroy]

  def invite_someone
    @invitation = Invitation.new
   @invitation.meeting = @meeting #for pundit do not delete
    authorize @invitation
  end

  def new
    @invitation = Invitation.new(meeting: @meeting)
    @team.users.each do |user|
      invitation =Invitation.new(user: user, meeting: @meeting)
      invitation.save
    end
    authorize @invitation

  end

  def create
    @user = User.find(invitation_params[:user_id])
    @invitation = Invitation.new(meeting: @meeting, user: @user)
    authorize @invitation
    if  @invitation.save
      redirect_to edit_organization_team_meeting_invitation_path(@organization, @team, @meeting, @invitation), notice: 'El invitado fue agregado'
    else
      redirect_to edit_organization_team_meeting_invitation_path(@organization, @team, @meeting, @invitation), notice: 'El invitado no pudo ser agregado'

    end
  end

  def edit
    @invitation = @meeting.invitations.first
    authorize @invitation
  end
  def update

  end
  def send_invites

  end

  def destroy
    @invitation = Invitation.find(params[:id])
    authorize @invitation
    @invitation.destroy!
    redirect_to edit_organization_team_meeting_invitation_path(@invitation.meeting.organization, @invitation.meeting.team, @invitation.meeting), notice: 'El invitado fue eliminado'
  end

  private
  def invitation_params
    params.require(:invitation).permit(:user_id)
  end
  def find_organization
    @organization = Organization.find(params[:organization_id])
  end
  def find_team
    @team = Team.find(params[:team_id])
  end
  def find_meeting
    @meeting = Meeting.find(params[:meeting_id])
  end
end

app/views/invitations/_form.html.erb
<h1>Invitados</h1>
<h3>Equipo: <%= link_to @team.name, organization_team_path(@organization, @team) %></h3>
<ul>
  <%@meeting.invitations.each do |invitation|%>
    <li>
      <%= invitation.user.name%> <%=invitation.user.last_name%>
        <% if  @meeting.user == invitation.user %>
           <strong>Owner</strong>
        <% else %>
          <%= link_to "Anular invitation", invitation_path(invitation.id), method: :delete, data: { confirm: "Confirme esta acción por favor" }  %>
        <% end %>
    </li>
  <% end %>
  <% if  (@organization.users - @meeting.users).empty?%>
    <p>Ya todas las personas de <%= @organization.name %> han sido invitadas</p>
  <% else %>
    <p><%= link_to "Agregar invitados a la reunión", invite_someone_organization_team_meeting_invitations_path(@organization, @team, @meeting) %></p>
  <% end %>
</ul>

app/views/invitations/edit.html.erb
<%= render 'form' %>

app/views/invitations/invite_someone.html.erb
<%= simple_form_for [@organization, @team, @meeting, @invitation] do |f| %>
    <%= f.association :user, label: 'Correo de la persona dentro de la organizazión que quiere invitar', collection: (@organization.users - @meeting.users)%>
<%= f.submit %>
<% end %>

<!-- (@invitation, method: :post, url:invite_someone_organization_team_meeting_invitations(@organization, @team, @meeting, @invitation)) -->

app/views/invitations/new.html.erb
<%= render 'form' %>
<p>eliminar esta reunion</p>
<p>link to crear reunion y enviar invitaciones</p>