config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'welcome', to: 'pages#welcome', as: :welcome

  get 'parse', to: 'pages#email_parse', as: :email_parse
  post 'parse', to: 'pages#email_parse'
  post 'email_processor', to: 'griddler/emails#create'

  resources :organizations do
    resources :teams, only: [:show, :new, :edit, :create, :update] do
      resources :participations, only:[:new, :create, :destroy]
      resources :meetings, only:[:index,:show, :new, :edit, :create, :update] do
        resources :invitations, only:[:new, :create, :edit] do
          collection do
            get :invite_someone
            post :send_invites

          end
        end
      end
    end
  end
  resources :teams, only: [:destroy]
  resources :meetings, only: [:destroy]
  resources :invitations, only:[:destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :teams
  has_many :participations, through: :teams
  has_many :users, through: :teams
  validates :name, presence: true
  validates :legal_id, presence: true
  validates :contact_email, presence: true
   # validates :legacy_code, format: { with: /\A[a-zA-Z]+\z/,  message: "only allows letters" }
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only:[:show, :edit, :update]
  def index
    @organizations = policy_scope(Organization)
  end

  def show
    authorize @organization
  end

  def new
    @organization = Organization.new
    authorize @organization
  end

  def create
    @organization = Organization.new(organization_params)
    if @organization.save
      redirect_to organization_path(@organization), notice: 'La Organización fue creada'
    else
      render :new
    end
    authorize @organization
  end

  def edit
    authorize @organization
  end

  def update
    @organization.update(organization_params)
    redirect_to organization_path(@organization)
    authorize @organization
  end

  private
  def organization_params
    params.require(:organization).permit(:name, :legal_id, :contact_email)

  end
  def set_organization
    @organization =Organization.find(params[:id])
  end

end

app/views/organizations/_form.html.erb
<%= simple_form_for @organization do |f| %>
<%= f.input :name  %>
<%= f.input :legal_id %>
<%= f.input :contact_email %>
<%= f.submit %>
<% end %>

app/views/organizations/index.html.erb
<h1>Todas las Organizaciones</h1>
<% @organizations.each do |org|%>
  <h5><%=link_to org.name, organization_path(org)%></h5>
  <p>Cedula Juridica: <%= org.legal_id%></p>
  <p>Contacto: <%= org.contact_email %></p>
<% end %>

app/views/organizations/show.html.erb
<h1>Organizacion:<%= @organization.name %></h1>
<%  if policy(@organization).edit?  %>
  <%= link_to "Editar", edit_organization_path(@organization)%>
<% end %>


<p>Cedula Juridica: <%= @organization.legal_id%></p>
<p>Contacto: <%= @organization.contact_email %></p>
<p>Equipos:</p>
<ul>
  <% @organization.teams.each do |team| %>

  <li><%= link_to team.name, organization_team_path(@organization, team)%></li>
  <% end %>
</ul>

  <%= link_to "Añadir Equipo", new_organization_team_path(@organization) %>